/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Danish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Skift til',
  'fabric.atlassianSwitcher.switchToTooltip': 'Skift til ...',
  'fabric.atlassianSwitcher.recent': 'Seneste',
  'fabric.atlassianSwitcher.more': 'Mere',
  'fabric.atlassianSwitcher.try': 'Prøv',
  'fabric.atlassianSwitcher.manageList': 'Administrér liste',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-projekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-område',
  'fabric.atlassianSwitcher.people': 'Personer',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'Se flere',
  'fabric.atlassianSwitcher.browseApps': 'Gennembladr Marketplace-apps',
  'fabric.atlassianSwitcher.errorHeading': 'Something’s gone wrong',
  'fabric.atlassianSwitcher.errorText':
    'Vi registrerer disse fejl, men du er velkommen til at kontakte os, hvis problemet ikke løses, når du genindlæser',
  'fabric.atlassianSwitcher.errorImageAltText':
    'En ødelagt robot og en flok mennesker er i gang med at ordne det.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'We couldn’t load this list. Please reload the page and try again.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'You’ve been logged out. Please log in again.',
  'fabric.atlassianSwitcher.login': 'Log in',
  'fabric.atlassianSwitcher.show.more.sites': 'Show more sites',
};
