/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Spanish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Cambiar a',
  'fabric.atlassianSwitcher.switchToTooltip': 'Cambiar a…',
  'fabric.atlassianSwitcher.recent': 'Recientes',
  'fabric.atlassianSwitcher.more': 'Más',
  'fabric.atlassianSwitcher.try': 'Pruébalo',
  'fabric.atlassianSwitcher.manageList': 'Administrar lista',
  'fabric.atlassianSwitcher.jiraProject': 'Proyecto Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Espacio de Confluence',
  'fabric.atlassianSwitcher.people': 'Personas',
  'fabric.atlassianSwitcher.administration': 'Administración',
  'fabric.atlassianSwitcher.discoverMore': 'Descubrir más',
  'fabric.atlassianSwitcher.browseApps': 'Explorar aplicaciones de Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Algo ha ido mal',
  'fabric.atlassianSwitcher.errorText':
    'Aunque nos encargamos de supervisar estos errores, no dudes en contactar con nosotros si se repiten después de actualizar la página.',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Un robot estropeado y varias personas arreglándolo.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'No hemos podido cargar esta lista. Vuelve a cargar la página e inténtalo de nuevo.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'Tu sesión ha finalizado. Vuelve a iniciarla.',
  'fabric.atlassianSwitcher.login': 'Iniciar sesión',
  'fabric.atlassianSwitcher.show.more.sites': 'Mostrar más sitios',
};
