/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Korean
export default {
  'fabric.atlassianSwitcher.switchTo': '다음으로 전환',
  'fabric.atlassianSwitcher.switchToTooltip': '다음으로 전환...',
  'fabric.atlassianSwitcher.recent': '최근 항목',
  'fabric.atlassianSwitcher.more': '더 보기',
  'fabric.atlassianSwitcher.try': '시도',
  'fabric.atlassianSwitcher.manageList': '목록 관리',
  'fabric.atlassianSwitcher.jiraProject': 'Jira 프로젝트',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence 스페이스',
  'fabric.atlassianSwitcher.people': '사용자',
  'fabric.atlassianSwitcher.administration': '관리',
  'fabric.atlassianSwitcher.discoverMore': '자세히 살펴보기',
  'fabric.atlassianSwitcher.browseApps': 'Marketplace 앱 찾아보기',
  'fabric.atlassianSwitcher.errorHeading': '문제가 발생했습니다.',
  'fabric.atlassianSwitcher.errorText':
    '이 오류를 추적하고 있습니다. 페이지를 새로 고쳐도 문제가 해결되지 않는 경우 저희에게 문의해 주시기 바랍니다.',
  'fabric.atlassianSwitcher.errorImageAltText':
    '고장 난 로봇과 이를 고치는 여러 사람들입니다.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    '이 목록을 로드하지 못했습니다. 새로 고치고 다시 시도해주세요.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    '로그아웃되었습니다. 다시 로그인해주세요.',
  'fabric.atlassianSwitcher.login': '로그인',
  'fabric.atlassianSwitcher.show.more.sites': '사이트 더 보기',
};
