/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Swedish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Byt till',
  'fabric.atlassianSwitcher.switchToTooltip': 'Växla till ...',
  'fabric.atlassianSwitcher.recent': 'Senaste',
  'fabric.atlassianSwitcher.more': 'Mer',
  'fabric.atlassianSwitcher.try': 'Prova',
  'fabric.atlassianSwitcher.manageList': 'Hantera lista',
  'fabric.atlassianSwitcher.jiraProject': 'Jira-projekt',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence-utrymme',
  'fabric.atlassianSwitcher.people': 'Personer',
  'fabric.atlassianSwitcher.administration': 'Administration',
  'fabric.atlassianSwitcher.discoverMore': 'Upptäck mer',
  'fabric.atlassianSwitcher.browseApps': 'Sök app på Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Något gick fel',
  'fabric.atlassianSwitcher.errorText':
    'Vi håller koll på dessa fel, men tveka inte att kontakta oss om en uppdatering inte åtgärdar problemen.',
  'fabric.atlassianSwitcher.errorImageAltText':
    'En trasig robot och ett antal personer arbetar för att åtgärda felet.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Vi kunde inte läsa in listan. Uppdatera sidan och försök igen.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'Du har loggats ut. Logga in igen.',
  'fabric.atlassianSwitcher.login': 'Logga in',
  'fabric.atlassianSwitcher.show.more.sites': 'Visa fler webbplatser',
};
