/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Thai
export default {
  'fabric.atlassianSwitcher.switchTo': 'เปลี่ยนเป็น',
  'fabric.atlassianSwitcher.switchToTooltip': 'เปลี่ยนเป็น...',
  'fabric.atlassianSwitcher.recent': 'ล่าสุด',
  'fabric.atlassianSwitcher.more': 'เพิ่มเติม',
  'fabric.atlassianSwitcher.try': 'ลอง',
  'fabric.atlassianSwitcher.manageList': 'จัดการรายการ',
  'fabric.atlassianSwitcher.jiraProject': 'โปรเจกต์ Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'พื้นที่ร่วม',
  'fabric.atlassianSwitcher.people': 'ผู้คน',
  'fabric.atlassianSwitcher.administration': 'ฝ่ายดูแลระบบ',
  'fabric.atlassianSwitcher.discoverMore': 'ผลิตภัณฑ์เพิ่มเติมของ Atlassian',
  'fabric.atlassianSwitcher.browseApps': 'เรียกดูแอป Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'มีบางอย่างผิดพลาด',
  'fabric.atlassianSwitcher.errorText':
    'เราจะติดตามข้อผิดพลาดเหล่านี้ แต่โปรดอย่าลังเลที่จะติดต่อเราหากการรีเฟรชไม่สามารถแก้ไขข้อผิดพลาดได้',
  'fabric.atlassianSwitcher.errorImageAltText':
    'เกิดข้อผิดพลาดบางประการ และเรากำลังทำการแก้ไขข้อผิดพลาดเหล่านั้น',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'เราไม่สามารถดาวน์โหลดรายการนี้ได้ โปรดดาวน์โหลดหน้าข้อมูลใหม่แล้วลองอีกครั้ง',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'คุณได้ออกจากระบบแล้ว โปรดเข้าสู่ระบบอีกครั้ง',
  'fabric.atlassianSwitcher.login': 'เข้าสู่ระบบ',
  'fabric.atlassianSwitcher.show.more.sites': 'แสดงเว็บไซต์เพิ่มเติม',
};
