/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Turkish
export default {
  'fabric.atlassianSwitcher.switchTo': 'Şuna geçin:',
  'fabric.atlassianSwitcher.switchToTooltip': 'Şuna geçin…',
  'fabric.atlassianSwitcher.recent': 'En Son',
  'fabric.atlassianSwitcher.more': 'Devamı',
  'fabric.atlassianSwitcher.try': 'Deneyin',
  'fabric.atlassianSwitcher.manageList': 'Listeyi yönetin',
  'fabric.atlassianSwitcher.jiraProject': 'Jira projesi',
  'fabric.atlassianSwitcher.confluenceSpace': 'Confluence alanı',
  'fabric.atlassianSwitcher.people': 'Kişiler',
  'fabric.atlassianSwitcher.administration': 'Yönetim',
  'fabric.atlassianSwitcher.discoverMore': 'Daha fazla Atlassian projesi',
  'fabric.atlassianSwitcher.browseApps': 'Marketplace uygulamalarına göz atın',
  'fabric.atlassianSwitcher.errorHeading': 'Bir hata oluştu',
  'fabric.atlassianSwitcher.errorText':
    'Bu hataları takip ediyoruz, ancak sayfayı yenilemek sorunu çözmezse lütfen bizimle iletişime geçmekten çekinmeyin',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Bozuk bir robot ve robotu düzeltmeye çalışan insanlar.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Bu liste yüklenemedi. Lütfen sayfayı yeniden yükleyin ve tekrar deneyin.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'Oturumunuz kapatıldı. Lütfen yeniden oturum açın.',
  'fabric.atlassianSwitcher.login': 'Oturum aç',
  'fabric.atlassianSwitcher.show.more.sites': 'Daha fazla site göster',
};
