/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Ukrainian
export default {
  'fabric.atlassianSwitcher.switchTo': 'Перейти:',
  'fabric.atlassianSwitcher.switchToTooltip': 'Перехід на інший продукт',
  'fabric.atlassianSwitcher.recent': 'Нещодавні',
  'fabric.atlassianSwitcher.more': 'Більше',
  'fabric.atlassianSwitcher.try': 'Спробуйте',
  'fabric.atlassianSwitcher.manageList': 'Настроїти список',
  'fabric.atlassianSwitcher.jiraProject': 'Проект у Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Область Confluence',
  'fabric.atlassianSwitcher.people': 'Контакти',
  'fabric.atlassianSwitcher.administration': 'Адміністрування',
  'fabric.atlassianSwitcher.discoverMore': 'Інші продукти Atlassian',
  'fabric.atlassianSwitcher.browseApps': 'Додатки в Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Щось не так',
  'fabric.atlassianSwitcher.errorText':
    'Ми записуємо помилки, але якщо оновлення сторінки не вирішило проблеми, зверніться до нас',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Зламаний робот і люди, які намагаються його полагодити',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Список не завантажено. Оновіть сторінку та спробуйте знову.',
  'fabric.atlassianSwitcher.errorTextLoggedOut': 'Ви вийшли. Увійдіть знову.',
  'fabric.atlassianSwitcher.login': 'Увійти',
  'fabric.atlassianSwitcher.show.more.sites': 'Інші сайти',
};
