/**
 * NOTE:
 *
 * This file is automatically generated by i18n-tools.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 */
// Vietnamese
export default {
  'fabric.atlassianSwitcher.switchTo': 'Chuyển sang',
  'fabric.atlassianSwitcher.switchToTooltip': 'Chuyển sang…',
  'fabric.atlassianSwitcher.recent': 'Gần đây',
  'fabric.atlassianSwitcher.more': 'Khác',
  'fabric.atlassianSwitcher.try': 'Dùng thử',
  'fabric.atlassianSwitcher.manageList': 'Quản lý danh sách',
  'fabric.atlassianSwitcher.jiraProject': 'Dự án Jira',
  'fabric.atlassianSwitcher.confluenceSpace': 'Không gian Confluence',
  'fabric.atlassianSwitcher.people': 'Mọi người',
  'fabric.atlassianSwitcher.administration': 'Quản trị',
  'fabric.atlassianSwitcher.discoverMore': 'Các sản phẩm Atlassian khác',
  'fabric.atlassianSwitcher.browseApps': 'Duyệt các ứng dụng Marketplace',
  'fabric.atlassianSwitcher.errorHeading': 'Đã xảy ra lỗi',
  'fabric.atlassianSwitcher.errorText':
    'Chúng tôi sẽ theo dõi các lỗi này, nhưng vui lòng liên hệ với chúng tôi nếu bạn đã làm mới mà vẫn không khắc phục được lỗi',
  'fabric.atlassianSwitcher.errorImageAltText':
    'Một rô-bốt bị hỏng và một số người đang tìm cách sửa chữa.',
  'fabric.atlassianSwitcher.errorTextNetwork':
    'Chúng tôi không thể tải danh sách này. Vui lòng tải lại trang và thử lại.',
  'fabric.atlassianSwitcher.errorTextLoggedOut':
    'Bạn đã đăng xuất. Vui lòng đăng nhập lại.',
  'fabric.atlassianSwitcher.login': 'Đăng nhập',
  'fabric.atlassianSwitcher.show.more.sites': 'Hiển thị thêm trang web',
};
