/* eslint-disable global-require */
/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify build/icon/createIconDocs.js.
 * Add synonyms in icon/icons/synonyms.js.
 */

interface Data {
  keywords: string[];
  componentName: string;
  package: string;
}

const metaData: Record<string, Data> = {
  'archive/16': {
    keywords: [
      'archive/16',
      'archive16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Archive16Icon',
    package: '@atlaskit/icon-file-interface/glyph/archive/16',
  },
  'audio/16': {
    keywords: ['audio/16', 'audio16', 'file-interface', 'icon-file-interface'],
    componentName: 'Audio16Icon',
    package: '@atlaskit/icon-file-interface/glyph/audio/16',
  },
  'document/16': {
    keywords: [
      'document/16',
      'document16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Document16Icon',
    package: '@atlaskit/icon-file-interface/glyph/document/16',
  },
  'excel-spreadsheet/16': {
    keywords: [
      'excel-spreadsheet/16',
      'excelspreadsheet16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'ExcelSpreadsheet16Icon',
    package: '@atlaskit/icon-file-interface/glyph/excel-spreadsheet/16',
  },
  'executable/16': {
    keywords: [
      'executable/16',
      'executable16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Executable16Icon',
    package: '@atlaskit/icon-file-interface/glyph/executable/16',
  },
  'folder/16': {
    keywords: [
      'folder/16',
      'folder16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Folder16Icon',
    package: '@atlaskit/icon-file-interface/glyph/folder/16',
  },
  'generic/16': {
    keywords: [
      'generic/16',
      'generic16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Generic16Icon',
    package: '@atlaskit/icon-file-interface/glyph/generic/16',
  },
  'gif/16': {
    keywords: ['gif/16', 'gif16', 'file-interface', 'icon-file-interface'],
    componentName: 'Gif16Icon',
    package: '@atlaskit/icon-file-interface/glyph/gif/16',
  },
  'google-doc/16': {
    keywords: [
      'google-doc/16',
      'googledoc16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleDoc16Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-doc/16',
  },
  'google-form/16': {
    keywords: [
      'google-form/16',
      'googleform16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleForm16Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-form/16',
  },
  'google-sheet/16': {
    keywords: [
      'google-sheet/16',
      'googlesheet16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleSheet16Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-sheet/16',
  },
  'google-slide/16': {
    keywords: [
      'google-slide/16',
      'googleslide16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleSlide16Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-slide/16',
  },
  'image/16': {
    keywords: ['image/16', 'image16', 'file-interface', 'icon-file-interface'],
    componentName: 'Image16Icon',
    package: '@atlaskit/icon-file-interface/glyph/image/16',
  },
  'pdf-document/16': {
    keywords: [
      'pdf-document/16',
      'pdfdocument16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'PdfDocument16Icon',
    package: '@atlaskit/icon-file-interface/glyph/pdf-document/16',
  },
  'powerpoint-presentation/16': {
    keywords: [
      'powerpoint-presentation/16',
      'powerpointpresentation16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'PowerpointPresentation16Icon',
    package: '@atlaskit/icon-file-interface/glyph/powerpoint-presentation/16',
  },
  'presentation/16': {
    keywords: [
      'presentation/16',
      'presentation16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Presentation16Icon',
    package: '@atlaskit/icon-file-interface/glyph/presentation/16',
  },
  'sketch/16': {
    keywords: [
      'sketch/16',
      'sketch16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Sketch16Icon',
    package: '@atlaskit/icon-file-interface/glyph/sketch/16',
  },
  'source-code/16': {
    keywords: [
      'source-code/16',
      'sourcecode16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'SourceCode16Icon',
    package: '@atlaskit/icon-file-interface/glyph/source-code/16',
  },
  'spreadsheet/16': {
    keywords: [
      'spreadsheet/16',
      'spreadsheet16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Spreadsheet16Icon',
    package: '@atlaskit/icon-file-interface/glyph/spreadsheet/16',
  },
  'video/16': {
    keywords: ['video/16', 'video16', 'file-interface', 'icon-file-interface'],
    componentName: 'Video16Icon',
    package: '@atlaskit/icon-file-interface/glyph/video/16',
  },
  'word-document/16': {
    keywords: [
      'word-document/16',
      'worddocument16',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'WordDocument16Icon',
    package: '@atlaskit/icon-file-interface/glyph/word-document/16',
  },
  'archive/24': {
    keywords: [
      'archive/24',
      'archive24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Archive24Icon',
    package: '@atlaskit/icon-file-interface/glyph/archive/24',
  },
  'audio/24': {
    keywords: ['audio/24', 'audio24', 'file-interface', 'icon-file-interface'],
    componentName: 'Audio24Icon',
    package: '@atlaskit/icon-file-interface/glyph/audio/24',
  },
  'document/24': {
    keywords: [
      'document/24',
      'document24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Document24Icon',
    package: '@atlaskit/icon-file-interface/glyph/document/24',
  },
  'excel-spreadsheet/24': {
    keywords: [
      'excel-spreadsheet/24',
      'excelspreadsheet24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'ExcelSpreadsheet24Icon',
    package: '@atlaskit/icon-file-interface/glyph/excel-spreadsheet/24',
  },
  'executable/24': {
    keywords: [
      'executable/24',
      'executable24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Executable24Icon',
    package: '@atlaskit/icon-file-interface/glyph/executable/24',
  },
  'folder/24': {
    keywords: [
      'folder/24',
      'folder24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Folder24Icon',
    package: '@atlaskit/icon-file-interface/glyph/folder/24',
  },
  'generic/24': {
    keywords: [
      'generic/24',
      'generic24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Generic24Icon',
    package: '@atlaskit/icon-file-interface/glyph/generic/24',
  },
  'gif/24': {
    keywords: ['gif/24', 'gif24', 'file-interface', 'icon-file-interface'],
    componentName: 'Gif24Icon',
    package: '@atlaskit/icon-file-interface/glyph/gif/24',
  },
  'google-doc/24': {
    keywords: [
      'google-doc/24',
      'googledoc24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleDoc24Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-doc/24',
  },
  'google-form/24': {
    keywords: [
      'google-form/24',
      'googleform24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleForm24Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-form/24',
  },
  'google-sheet/24': {
    keywords: [
      'google-sheet/24',
      'googlesheet24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleSheet24Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-sheet/24',
  },
  'google-slide/24': {
    keywords: [
      'google-slide/24',
      'googleslide24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleSlide24Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-slide/24',
  },
  'image/24': {
    keywords: ['image/24', 'image24', 'file-interface', 'icon-file-interface'],
    componentName: 'Image24Icon',
    package: '@atlaskit/icon-file-interface/glyph/image/24',
  },
  'pdf-document/24': {
    keywords: [
      'pdf-document/24',
      'pdfdocument24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'PdfDocument24Icon',
    package: '@atlaskit/icon-file-interface/glyph/pdf-document/24',
  },
  'powerpoint-presentation/24': {
    keywords: [
      'powerpoint-presentation/24',
      'powerpointpresentation24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'PowerpointPresentation24Icon',
    package: '@atlaskit/icon-file-interface/glyph/powerpoint-presentation/24',
  },
  'presentation/24': {
    keywords: [
      'presentation/24',
      'presentation24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Presentation24Icon',
    package: '@atlaskit/icon-file-interface/glyph/presentation/24',
  },
  'sketch/24': {
    keywords: [
      'sketch/24',
      'sketch24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Sketch24Icon',
    package: '@atlaskit/icon-file-interface/glyph/sketch/24',
  },
  'source-code/24': {
    keywords: [
      'source-code/24',
      'sourcecode24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'SourceCode24Icon',
    package: '@atlaskit/icon-file-interface/glyph/source-code/24',
  },
  'spreadsheet/24': {
    keywords: [
      'spreadsheet/24',
      'spreadsheet24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Spreadsheet24Icon',
    package: '@atlaskit/icon-file-interface/glyph/spreadsheet/24',
  },
  'video/24': {
    keywords: ['video/24', 'video24', 'file-interface', 'icon-file-interface'],
    componentName: 'Video24Icon',
    package: '@atlaskit/icon-file-interface/glyph/video/24',
  },
  'word-document/24': {
    keywords: [
      'word-document/24',
      'worddocument24',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'WordDocument24Icon',
    package: '@atlaskit/icon-file-interface/glyph/word-document/24',
  },
  'archive/48': {
    keywords: [
      'archive/48',
      'archive48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Archive48Icon',
    package: '@atlaskit/icon-file-interface/glyph/archive/48',
  },
  'audio/48': {
    keywords: ['audio/48', 'audio48', 'file-interface', 'icon-file-interface'],
    componentName: 'Audio48Icon',
    package: '@atlaskit/icon-file-interface/glyph/audio/48',
  },
  'document/48': {
    keywords: [
      'document/48',
      'document48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Document48Icon',
    package: '@atlaskit/icon-file-interface/glyph/document/48',
  },
  'excel-spreadsheet/48': {
    keywords: [
      'excel-spreadsheet/48',
      'excelspreadsheet48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'ExcelSpreadsheet48Icon',
    package: '@atlaskit/icon-file-interface/glyph/excel-spreadsheet/48',
  },
  'executable/48': {
    keywords: [
      'executable/48',
      'executable48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Executable48Icon',
    package: '@atlaskit/icon-file-interface/glyph/executable/48',
  },
  'folder/48': {
    keywords: [
      'folder/48',
      'folder48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Folder48Icon',
    package: '@atlaskit/icon-file-interface/glyph/folder/48',
  },
  'generic/48': {
    keywords: [
      'generic/48',
      'generic48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Generic48Icon',
    package: '@atlaskit/icon-file-interface/glyph/generic/48',
  },
  'gif/48': {
    keywords: ['gif/48', 'gif48', 'file-interface', 'icon-file-interface'],
    componentName: 'Gif48Icon',
    package: '@atlaskit/icon-file-interface/glyph/gif/48',
  },
  'google-doc/48': {
    keywords: [
      'google-doc/48',
      'googledoc48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleDoc48Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-doc/48',
  },
  'google-form/48': {
    keywords: [
      'google-form/48',
      'googleform48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleForm48Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-form/48',
  },
  'google-sheet/48': {
    keywords: [
      'google-sheet/48',
      'googlesheet48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleSheet48Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-sheet/48',
  },
  'google-slide/48': {
    keywords: [
      'google-slide/48',
      'googleslide48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'GoogleSlide48Icon',
    package: '@atlaskit/icon-file-interface/glyph/google-slide/48',
  },
  'image/48': {
    keywords: ['image/48', 'image48', 'file-interface', 'icon-file-interface'],
    componentName: 'Image48Icon',
    package: '@atlaskit/icon-file-interface/glyph/image/48',
  },
  'pdf-document/48': {
    keywords: [
      'pdf-document/48',
      'pdfdocument48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'PdfDocument48Icon',
    package: '@atlaskit/icon-file-interface/glyph/pdf-document/48',
  },
  'powerpoint-presentation/48': {
    keywords: [
      'powerpoint-presentation/48',
      'powerpointpresentation48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'PowerpointPresentation48Icon',
    package: '@atlaskit/icon-file-interface/glyph/powerpoint-presentation/48',
  },
  'presentation/48': {
    keywords: [
      'presentation/48',
      'presentation48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Presentation48Icon',
    package: '@atlaskit/icon-file-interface/glyph/presentation/48',
  },
  'sketch/48': {
    keywords: [
      'sketch/48',
      'sketch48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Sketch48Icon',
    package: '@atlaskit/icon-file-interface/glyph/sketch/48',
  },
  'source-code/48': {
    keywords: [
      'source-code/48',
      'sourcecode48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'SourceCode48Icon',
    package: '@atlaskit/icon-file-interface/glyph/source-code/48',
  },
  'spreadsheet/48': {
    keywords: [
      'spreadsheet/48',
      'spreadsheet48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'Spreadsheet48Icon',
    package: '@atlaskit/icon-file-interface/glyph/spreadsheet/48',
  },
  'video/48': {
    keywords: ['video/48', 'video48', 'file-interface', 'icon-file-interface'],
    componentName: 'Video48Icon',
    package: '@atlaskit/icon-file-interface/glyph/video/48',
  },
  'word-document/48': {
    keywords: [
      'word-document/48',
      'worddocument48',
      'file-interface',
      'icon-file-interface',
    ],
    componentName: 'WordDocument48Icon',
    package: '@atlaskit/icon-file-interface/glyph/word-document/48',
  },
};

export default metaData;
